### ISSUE TITLE
Bad scoring for parent phase

### ISSUE THREAD

**Issue by Didayolo** [zhengying-liu/autodl#5]
The score displayed for "All datasets" phase is the score of dataset 1.

![screen1](https://user-images.githubusercontent.com/11784999/56134313-a3d2b280-5f8e-11e9-90e9-b0a5e740a0b9.png)
![screen2](https://user-images.githubusercontent.com/11784999/56134321-a6cda300-5f8e-11e9-90b2-27fbde56c9d9.png)

_The issue can come from Codalab or from the Parent Scoring Program._

**Comment by zhengying-liu** [comment]
Since the score of parent phase (which should be the average ranking among all participants) cannot be computed in scoring program, now we always set it to 0.
