### ISSUE TITLE
Auto-migration

### ISSUE THREAD

**Issue by madclam** [zhengying-liu/autodl#8]
In single phase competitions, auto-migration should be set to False.

Here are the correct settings:

PARENT PHASE
Results Scoring Only => YES
Auto migration => NO
If submission beats old score, put submission on leaderboard => NO
Ingestion program only during scoring => NO
Is parallel parent => YES

CHILDREN PHASES
Results Scoring Only => YES
Auto migration => NO
If submission beats old score, put submission on leaderboard => NO
Ingestion program only during scoring => YES
Is parallel parent => NO

**Comment by zhengying-liu** [comment]
Fixed in the file `competition.yaml` in the commit f3f89fcbea216539e34357f26db32fd47f9a13b8
