### ISSUE TITLE
recommend to install nvidia-dali package

### ISSUE THREAD

**Issue by tanglang96** [zhengying-liu/autodl#9]
I hope you can consider to install this package, it's quite useful
https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/installation.html

**Comment by zhengying-liu** [comment]
Hi, thanks for the suggestion. I added this package here (commented) in the [Dockerfile](https://github.com/zhengying-liu/autodl/blob/master/docker/Dockerfile). If another request concerns the same package, we'll install it and update the Docker image.
